global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'serverwatch'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  # System metrics from target servers
  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'
        labels:
          env: 'production'
      - targets:
          - '172.22.2.174:9100'
          - '172.22.2.136:9100'
        labels:
          env: 'production'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
